### ISSUE TITLE
Implement final feedback

### ISSUE THREAD

**Issue by nfejzic** [nfejzic/natural_computation#1]
# Feedback

The basic structure and the linguistic quality of the work are good, but there
are some important issues to be addressed (more details in the notes in the
paper):

- it is never clear what the goal of the work is, yes, analysis of output
  patterns, but what do we analyze and why?

- the description of weight init methods is rather confusing, all of them should
  be explained properly in the corresponding section

- figures and tables must be referenced in the text, the captions should be as
  nice as in the result section

- if you use this class/non-class measure, then of course, you have to explain
  this concept, which should be a section in ANNs, because it is never explained
  anyway how classification is performed by the ANN

- you should not make any new experiments, but describe the ones you made
  correctly, and also give some motivation for it, this correlates to the first
  point of explaining what and why you are doing these things

- write a proper summary

# TODO:

## Feedback on page 1

- [x] Address issues in abstract
- [x] #2

### Section 2.1

- [x] Remove the "General Information" title
- [x] Address the "inventions"
- [x] Correctly cite
- [x] Address the "summed"
- [x] Grammar corrections (with -> in, then -> ~then~, some -> a specific)
- [x] Address the "etc. and"

### Section 2.2

- [x] Correctly cite
- [x] Accuraccy and error comment
- [x] Remove the "and thus learn the same feature"
- [x] Variance of what?
- [x] Variance vs gradient, what is the connection, if any?
- [x] Address the general comment

### Section 2.3

- [x] Random init "improves" the gradient? Explain
- [x] symmetry breaking -> symmetry-breaking (?)
- [x] Explain: much greater results?
- [x] Remove "close to zero" (?)

### Section 2.3 (continued)

- [x] Learning the same feature
- [x] Comment regarding - "however, the problem is caused by weight init"

### Section 2.4

- [x] Write Xavier with capital 'X'
- [x] Number the equation
- [x] Explain the idea of the formula
- [x] Correctly explain the Xavier:
  - r is different for each layer
  - Xavier draws from normal, not uniform distribution

### Section 2.5

- [x] ANN's -> ANN
- [x] address the comma, maybe change to dot and start a new sentence?
- [x] altough -> ~altough~
- [x] map more complex data -> it can make more complex mapping of the data
- [x] showcase -> show (maybe?)

### Section 2.5.1

- [x] Binary Step -> maybe rename to Step Function (see comment)
- [x] First sentence either reword or remove
- [x] First point is wrong, we need to change that

### Section 2.5.1 (continued)

- [x] back propagation -> back-propagation
- [x] gradient is not a function
- [x] refer to figure in text (where?)

### Section 2.5.2

- [x] non-linear -> nonlinear (?)
- [x] function's gradient -> what to do here?

### Section 2.5.3

- [x] outputs -> reword this

### Section 2.5.3 (continued)

- [x] why does the vanishing gradient occur here?

### Section 2.5.4

- [x] back propagation -> back-propagation
- [x] in the ANN at the same time - reword or remove (somehow)
- [x] back propagation -> back-propagation
- [x] this issue -> which issue? dead neurons issue?

### Section 2.5.5

- [x] As a newly -> remove this?
- [x] underlying pattenrs -> remove or reword?

### Section 3

- [x] Experiment setup explanation is vague. Explain more, in particular the
      goal.

### Section 3.1

- [x] should be integrated in the "Experiment Setup"?
- [x] database -> dataset
- [x] similarly designed with precision -> reword
- [x] in practice -> ~in practice~

### Section 3.1.1

- [x] great performance -> reword, what kind of performance
- [x] was it even trained -> clarify that we did not train the CNN
- [x] remove the detail about changing shape of the images.

### Section 3.1.2

- [x] different outputs -> reword this
- [x] First explain the structure, then variations; see second point for an
      example (?)
- [x] Output layer point -> last sentence is not clear enough

### Section 3.1.3

- [x] Used -> ~Used~ (in the title)

### Section 3.1.3 (continued)

- [x] Do not explain techniques, refer to previous sections
- [x] Move (part of) explanation for Xavier to Weight Init Section
- [x] Random Normal Init -> explained differently here, which one is correct?
- [x] If we do not use Alternating init, don't describe it. If we do, clarify
      how.

### Section 3.2

- [x] Explained the metrics too late

### Section 3.2.1

- [x] Accuracy is not interesting
- [x] Re-write formula in an obscure way that needs a legen to interpret, like a
      real scientist! 🙄

### Section 3.2.2

- [x] confidence -> reword/explain
- [x] Class and Non-Class not explained before, not clear what this means

### Section 3.2.2 (continued)

- [x] Re-write formulas, remember to do it like a scientist!
- [x] No variance of output values, add this

### Section 4

- [x] Reference section on activation funcions
- [x] Prof. does not understand the other metric
  - I explained the metric now, but I don't know how the values should be read. @Fleton maybe explain this further? Explain, whether a high or low value is wanted etc. 
- [x] Did we alternate?
- [x] What about the variance

## Feedback on page 11

- [x] something on function, don't know what is wanted
- [x] is low difference good or bad?
  - we don't actually know, that wasn't our goal? Maybe put in "further work", that someone should now train networks based on these findings, and tell us what is a good starting point? 
  - According to Prof.:
    > Fiel mir heute noch ein, da uns die output patterns vor allem im Hinblick auf die target values interessieren, sollte eine Masszahl sein, wie weit der Mittelwert der class values vom MIttelwert der non-class values entfernt ist, das waere eigentlich das Traumergebnis, dass man eine Init findet, die diese Distanz moeglichst gross macht, das wird man nicht wirlklich steuern koennen, aber vielleicht gibt es Inits, die da besser sind
   
   So a high difference should be good? 
- [x] accuracy is not important, something else?
  - I added variance in results (Nadir)

### Section 5 - Conclusion

- [x] Rewrite conclusion:
  - [x] Describe the work and goals; no-one cares about introduction to ANN
  - [x] Summarize the main results
  - [x] Discuss results
  - [x] Give ideas for further work
